<a href="https://colab.research.google.com/github/JUMITO737/Regresion_Logistica/blob/main/Act_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Actividad 7 (Regresión Logística)

1. **Utilizar** el nuevo repositorio con el nombre: **Regresión Logistica**

2. **Agregar** el archivo: **“Cuentas_credicel.csv”**

3. **Realiza** las acciones de preprocesamiento necesarias: **Nulos y Outliers**

4. **Analizar** 10 casos de correlación logística que existe entre diferentes variables de nuestra base de datos, aplicando la herramienta de **“Regresión Logística”**

5. **Convertir** las variables **que sean necesarias** en variables de tipo  dicotómica con las categorías que se consideren pertinentes, aplicando la herramienta de  **“Regresión Logística”**

6. **Realizar** una tabla de todos los coeficientes de **precisión, exactitud y sensibilidad** obtenidos para cada correlación analizada, según sea el caso.

7. **Crear** los archivos requeridos en **Google Colab** y respaldarlos en **GitHub.**

8. **Generar** un reporte comparativo sobre los análisis realizados y subirlo a **GitHub, en formato pdf.**

9. **Subir** el link del repositorio en CANVAS para **“Evaluación”**

## Librerias :

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

## Archivos :

In [2]:
df = pd.read_csv('cuentas_credicel.csv', encoding='latin-1')
df.head(5)

<ipython-input-2-c71743e22efc>:1: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('cuentas_credicel.csv', encoding='latin-1')


folio       tag  folio_solicitud             fecha     marca  \
0         3  HDNAWQ3A               30  12/11/2021 19:00       ZTE   
1         4  M418YNR4               33  12/11/2021 19:15  MOTOROLA   
2         5  SZ7V3NZT               37  13/11/2021 14:13       ZTE   
3         6  9I08UIQZ               38  13/11/2021 15:45       ZTE   
4         7  JMF4LKYU               44  13/11/2021 16:10  MOTOROLA   

                         modelo plazo  precio  enganche  descuento  ...  \
0            Blade A3 2020 RO B   26S  1949.0     780.0        0.0  ...   
1  LTE XT2097-12 E7I POWER Azul   13S  2999.0    1050.0        0.0  ...   
2            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0  ...   
3            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0  ...   
4                         G10 B   39S  4299.0    1075.0        0.0  ...   

   porc_eng  limite_credito  semana_actual  cp_cliente edad_cliente  \
0     40.02            5000             26         NaN         23.0   
1     35.01            6000             13         NaN         60.0   
2     25.01               0             74         NaN         58.0   
3     25.01            7000             13         NaN         42.0   
4     25.01            7000             74         NaN         33.0   

    cd_cliente  edo_cliente                    cd_venta edo_venta  \
0            0            0                   Tantoyuca  Veracruz   
1      PUEBLA          PUE.  Heroica Puebla de Zaragoza    Puebla   
2    TANTOYUCA         VER.                           0         0   
3  AMXTLAN PUE          NaN                    Zacatlan    Puebla   
4   TANTOYUCA          VER.                   Tantoyuca  Veracruz   

                 curp  
0  AEVM980413MVZNDR02  
1  ZALC610119MPLPRR07  
2                   0  
3  SAMJ790115MPLNRS02  
4  TEHF880707HVZRRR07  

[5 rows x 39 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   folio            22735 non-null  int64  
 1   tag                 22735 non-null  object 
 2   folio_solicitud     22735 non-null  int64  
 3   fecha               22735 non-null  object 
 4   marca               22735 non-null  object 
 5   modelo              22735 non-null  object 
 6   plazo               22735 non-null  object 
 7   precio              22735 non-null  float64
 8   enganche            22735 non-null  float64
 9   descuento           22735 non-null  float64
 10  semana              22735 non-null  int64  
 11  monto_financiado    22735 non-null  float64
 12  costo_total         22735 non-null  int64  
 13  monto_accesorios    22735 non-null  float64
 14  agente_venta        22735 non-null  object 
 15  dis_venta           22735 non-null  object 
 16  stat

## Limpieza :

### Valores Nulos

In [4]:
df.isnull().sum()

folio                 0
tag                      0
folio_solicitud          0
fecha                    0
marca                    0
modelo                   0
plazo                    0
precio                   0
enganche                 0
descuento                0
semana                   0
monto_financiado         0
costo_total              0
monto_accesorios         0
agente_venta             0
dis_venta                0
status                   0
fraude                   0
empresa                 13
inversion                0
pagos_realizados         0
reautorizacion           0
fecha_ultimo_pago     3356
fecha_pago_proximo    3356
status_cuenta         3314
puntos                   0
riesgo                   0
score_buro               0
razones_buro          7340
porc_eng                 0
limite_credito           0
semana_actual            0
cp_cliente            7243
edad_cliente             9
cd_cliente               0
edo_cliente              8
cd_venta                 0
e

In [5]:
df1 =df.fillna(method="bfill")
df1.isnull().sum()

folio               0
tag                    0
folio_solicitud        0
fecha                  0
marca                  0
modelo                 0
plazo                  0
precio                 0
enganche               0
descuento              0
semana                 0
monto_financiado       0
costo_total            0
monto_accesorios       0
agente_venta           0
dis_venta              0
status                 0
fraude                 0
empresa                0
inversion              0
pagos_realizados       0
reautorizacion         0
fecha_ultimo_pago      0
fecha_pago_proximo     0
status_cuenta         35
puntos                 0
riesgo                 0
score_buro             0
razones_buro           0
porc_eng               0
limite_credito         0
semana_actual          0
cp_cliente             0
edad_cliente           0
cd_cliente             0
edo_cliente            0
cd_venta               0
edo_venta              0
curp                   0
dtype: int64

In [6]:
df1 = df1.fillna(method="ffill")
df1.isnull().sum()

folio              0
tag                   0
folio_solicitud       0
fecha                 0
marca                 0
modelo                0
plazo                 0
precio                0
enganche              0
descuento             0
semana                0
monto_financiado      0
costo_total           0
monto_accesorios      0
agente_venta          0
dis_venta             0
status                0
fraude                0
empresa               0
inversion             0
pagos_realizados      0
reautorizacion        0
fecha_ultimo_pago     0
fecha_pago_proximo    0
status_cuenta         0
puntos                0
riesgo                0
score_buro            0
razones_buro          0
porc_eng              0
limite_credito        0
semana_actual         0
cp_cliente            0
edad_cliente          0
cd_cliente            0
edo_cliente           0
cd_venta              0
edo_venta             0
curp                  0
dtype: int64

In [7]:
df1.isnull().sum().sum()

0

In [8]:
df1.shape

(22735, 39)

### Outliners

In [9]:
df1['limite_credito'] = pd.to_numeric(df1['limite_credito'], errors='coerce')
df1['limite_credito'].fillna(7000, inplace=True)

In [10]:
numeric_columns = df1.select_dtypes(include=['number'])
categoric_columns = df1.select_dtypes(include=['object'])

In [11]:
def remove_outliers_iqr(df1, column_name, threshold=1.5):
    Q1 = df1[column_name].quantile(0.25)
    Q3 = df1[column_name].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - threshold * IQR
    upper_bound = Q3 + threshold * IQR
    df1 = df1[(df1[column_name] >= lower_bound) & (df1[column_name] <= upper_bound)]
    return df1

for column in numeric_columns.columns:
    df1 = remove_outliers_iqr(df1, column)

res = pd.concat([df1, categoric_columns], axis = 1)

res.shape

(22735, 57)

In [12]:
numeric = res.select_dtypes(include=['number']).columns
df2 = res.dropna(subset=numeric)

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6294 entries, 7243 to 22732
Data columns (total 57 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   folio            6294 non-null   float64
 1   tag                 6294 non-null   object 
 2   folio_solicitud     6294 non-null   float64
 3   fecha               6294 non-null   object 
 4   marca               6294 non-null   object 
 5   modelo              6294 non-null   object 
 6   plazo               6294 non-null   object 
 7   precio              6294 non-null   float64
 8   enganche            6294 non-null   float64
 9   descuento           6294 non-null   float64
 10  semana              6294 non-null   float64
 11  monto_financiado    6294 non-null   float64
 12  costo_total         6294 non-null   float64
 13  monto_accesorios    6294 non-null   float64
 14  agente_venta        6294 non-null   object 
 15  dis_venta           6294 non-null   object 
 16  st

In [14]:
df2.isnull().sum().sum()

0

## Actividad :

In [96]:
df2.sample(10)

folio       tag  folio_solicitud             fecha     marca  \
17286   17460.0  XLPP82O1          71080.0  06/02/2023 17:44  MOTOROLA   
15605   15767.0  ZZ4GD1OI          64350.0  15/01/2023 19:44  MOTOROLA   
13885   14038.0  6U89PDH9          57638.0  27/12/2022 12:45   SAMSUNG   
21698   21903.0  BRBU2UKY          63629.0  05/04/2023 14:32  Motorola   
20934   21123.0  VFUOO1S7          88156.0  26/03/2023 12:01   SAMSUNG   
22482   22719.0  LKVSAY5I          95393.0  15/04/2023 19:31       ZTE   
15145   15307.0  4718QG0T          40668.0  09/01/2023 18:49   SAMSUNG   
15685   15847.0  YQ8HT7TA          64750.0  17/01/2023 09:55   Samsung   
13922   14075.0  DG19W7XP          57795.0  27/12/2022 17:17   Samsung   
12845   12998.0  SOGZ781Q          51645.0  17/12/2022 20:28   Samsung   

                              modelo plazo   precio  enganche  descuento  ...  \
17286  4G XT2239-17 E22I  Blanco Kit   39S  3508.83     762.0        0.0  ...   
15605                       MOTO G31   39S  6250.00    1606.0        0.0  ...   
13885     4G SM-A042M A04E  Azul Kit   13S  2689.83     676.0        0.0  ...   
21698                      Moto E22i   26S  4700.00    1294.0        0.0  ...   
20934     4G SM-A047M A04S Negro Kit   26S  4598.85    1636.0        0.0  ...   
22482     4G BLADE A52 LITE Gris Kit   26S  2572.83     380.0        0.0  ...   
15145     4G SM-A042M A04E  Azul Kit   26S  2689.83     705.0        0.0  ...   
15685                            A04   26S  3349.00     772.0      400.0  ...   
13922                            A03   39S  4300.00     954.0        0.0  ...   
12845                            A04   13S  3549.00     639.0      400.0  ...   

       fecha_ultimo_pago  fecha_pago_proximo  status_cuenta  razones_buro  \
17286   15/04/2023 00:00    24/04/2023 00:00      Corriente   D7,F7,J0,M1   
15605   11/04/2023 00:00    20/04/2023 00:00      Corriente   E2,E0,J0,G1   
13885   03/01/2023 00:00    10/01/2023 00:00           Mora   K0,J0,F7,E4   
21698   12/04/2023 00:00    19/04/2023 00:00      Corriente   K0,J0,D7,D8   
20934   16/04/2023 00:00    23/04/2023 00:00      Corriente   K0,D7,J0,E2   
22482   15/04/2023 19:31    22/04/2023 00:00      Corriente   K0,J0,P9,E2   
15145   18/04/2023 00:00    25/04/2023 00:00      Corriente   K0,J0,E2,D7   
15685   11/04/2023 00:00    18/04/2023 00:00      Corriente   K0,J0,D7,D8   
13922   08/04/2023 00:00    22/04/2023 00:00      Corriente   E2,A1,J0,E0   
12845   11/03/2023 00:00    18/03/2023 00:00      Corriente   E2,J0,G1,E0   

      cp_cliente           cd_cliente  edo_cliente  \
17286      95600        PLAYA VICENTE          VER   
15605      65550    CIENEGA DE FLORES           NL   
13885      73450  HUITZILAN DE SERDAN          PUE   
21698      67196            GUADALUPE           NL   
20934      92810               TUXPAN          VER   
22482      72490               PUEBLA          PUE   
15145      95600        PLAYA VICENTE          VER   
15685      97700              TIZIMIN          YUC   
13922      25870      CASTA&Ntilde;OS         COAH   
12845      24920           DZITBALCHE         CAMP   

                         cd_venta             edo_venta                curp  
17286               Playa Vicente              Veracruz  LOPJ790322HVZPMS09  
15605           Cienega De Flores            Nuevo Leon  JIGJ020702HTCMNSA3  
13885                 Zacapoaxtla                Puebla  HEMS641128MPLRNT02  
21698                   Guadalupe            Nuevo Leon  EUSS640208MNLSPF05  
20934                      Tuxpan              Veracruz  CASZ760502HVZSSN05  
22482  Heroica Puebla De Zaragoza                Puebla  BARE880419MVZDPM02  
15145               Playa Vicente              Veracruz  PEOG801024MVZRSB09  
15685                     Tizimin               Yucatan  TICY820531MYNNND00  
13922                    Monclova  Coahuila De Zaragoza  CABM910529HCLRRX03  
12845                     Calkini              Campeche  CAUS760630HCCCHL08  

In [16]:
df_coef = pd.DataFrame(columns=['Variable', 'Analisis', 'Precision', 'Exactitud','Sensibilidad'])

### Remplazador de variables

In [17]:
df3 = df2.copy()

In [95]:
unico = np.unique(df2['riesgo'])
print(unico)

[-38.   -37.8  -37.75 ...  42.7   43.25  50.  ]


1 = Relacionado con Celular

0 = No relacionado con celulares

In [19]:
#df3['marca']= df3['marca'].replace(['ALCATEL', 'Alcatel', 'HISENSE', 'Hisense', 'MOTOROLA', 'Motorola', 'NOKIA', 'Nokia', 'SAMSUNG','Samsung', 'TCL', 'TECHPAD', 'TECNO MOBILE', 'VIVO', 'Vivo','WIKO', 'ZTE'], "1")
#df3['marca']= df3['marca'].replace(['LG','Lanix','RT'], "0")
#df3.sample(5)

In [20]:
#df3['marca'] = pd.to_numeric(df3['marca'])

In [ ]:
unico2 = np.unique(df2['agente_venta'])
unico2

### Analisis 1

In [22]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['puntos']

In [23]:
X= Vars_Indep
y= Var_Dep

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [25]:
escalar = StandardScaler()

In [26]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [27]:
algoritmo = LogisticRegression()

In [28]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
y_pred = algoritmo.predict(X_test)
y_pred

array([11., 11., 12., ..., 11., 11., 12.])

#### Coeficientes :

In [30]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[  0   0   0   0   0   1   0   0   0   0   0   0]
 [  0   0   0   2   0   3   0   0   0   0   0   0]
 [  0   0   0  11   0   6   1   2   4   0   0   0]
 [  0   0   0  38   0 141   3   3   7   0   0   0]
 [  0   0   0   8   0 186  13   7   1   0   0   0]
 [  0   0   0   9   0 500  71  15   7   0   0   0]
 [  0   0   0   5   0 265 114  31   5   0   0   0]
 [  0   0   0   1   0  67 106  56   4   0   0   0]
 [  0   0   0   0   0  26  38  57   8   0   0   0]
 [  0   0   0   0   0   4   9  27   4   0   0   0]
 [  0   0   0   0   0   2   5  12   1   0   0   0]
 [  0   0   0   1   0   0   0   2   0   0   0   0]]


In [31]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.14157716345870355


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.13343681377838354


In [33]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.12306848171900193


In [34]:
df_coef.loc[0] = ['puntos', '1', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 2

In [35]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['costo_total']

In [36]:
X= Vars_Indep
y= Var_Dep

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [38]:
escalar = StandardScaler()

In [39]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [40]:
algoritmo = LogisticRegression()

In [41]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [42]:
y_pred = algoritmo.predict(X_test)
y_pred

array([4914., 6292., 4056., ..., 4914., 5070., 6552.])

#### Coeficientes :

In [43]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [44]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.0008780734048631397


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [45]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.007991515652805975


In [46]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.0014193402300789449


In [47]:
df_coef.loc[1] = ['costo_total', '2', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 3

In [48]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['semana']

In [49]:
X= Vars_Indep
y= Var_Dep

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [51]:
escalar = StandardScaler()

In [52]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [53]:
algoritmo = LogisticRegression()

In [54]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [55]:
y_pred = algoritmo.predict(X_test)
y_pred

array([242., 183., 336., ..., 252., 189., 108.])

#### Coeficientes :

In [56]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [57]:
precision = precision_score(y_test, y_pred, average="micro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.020645844362096346


In [58]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.008075864415166698


In [59]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.0020883271857314706


In [60]:
df_coef.loc[2] = ['semana', '3', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 4

In [61]:
Vars_Indep= df2[['enganche', 'monto_financiado', 'descuento']]
Var_Dep= df3['status']

In [62]:
X= Vars_Indep
y= Var_Dep

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [64]:
escalar = StandardScaler()

In [65]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [66]:
algoritmo = LogisticRegression()

In [67]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [68]:
y_pred = algoritmo.predict(X_test)
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

#### Coeficientes :

In [69]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[1670    0    0]
 [ 217    0    0]
 [   2    0    0]]


In [70]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.2946885477324863


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [71]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.3333333333333333


In [72]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.3128219537323218


In [73]:
df_coef.loc[3] = ['status', '4', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 5

In [74]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['pagos_realizados']

In [75]:
X= Vars_Indep
y= Var_Dep

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [77]:
escalar = StandardScaler()

In [78]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [79]:
algoritmo = LogisticRegression()

In [80]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [81]:
y_pred = algoritmo.predict(X_test)
y_pred

array([9., 9., 0., ..., 0., 0., 0.])

#### Coeficientes :

In [82]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[324   0   2 ...   0   0   0]
 [ 55   0   0 ...   0   0   0]
 [ 90   0   2 ...   0   0   0]
 ...
 [  2   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [83]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.015825162126754038


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [84]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.03918336710230237


In [85]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.01914670412080467


In [86]:
df_coef.loc[4] = ['pagos_realizados', '5', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 6

In [87]:
#bins = [0, 1, 2, 3, 4, 5]  # Define los intervalos que dividen las etiquetas

# Utiliza pd.cut para discretizar las etiquetas continuas en categorías
#df2['riesgo'] = pd.cut(df2['riesgo'], bins)

In [104]:
Vars_Indep= df2[['precio', 'riesgo', 'descuento']]
Var_Dep= df2['enganche']

In [105]:
X= Vars_Indep
y= Var_Dep

In [106]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state =None)

In [107]:
escalar = StandardScaler()

In [108]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [109]:
algoritmo = LogisticRegression()

In [110]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [111]:
y_pred = algoritmo.predict(X_test)
y_pred

array([1000., 1000., 1000., ..., 1000., 1499., 1700.])

#### Coeficientes :

In [112]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [122]:
precision = precision_score(y_test, y_pred, average="weighted")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.0016090757273607976


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [123]:
sensibilidad = recall_score(y_test, y_pred, average="weighted")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.023828435266084195


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [125]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.002824690109804686


In [126]:
df_coef.loc[5] = ['enganche', '6', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 7

In [146]:
Vars_Indep= df2[['enganche', 'precio', 'riesgo']]
Var_Dep= df2['score_buro']

In [147]:
X= Vars_Indep
y= Var_Dep

In [148]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [149]:
escalar = StandardScaler()

In [150]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [151]:
algoritmo = LogisticRegression()

In [152]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [153]:
y_pred = algoritmo.predict(X_test)
y_pred

array([469., 478., 652., ..., 628., 469., 628.])

#### Coeficientes :

In [154]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [157]:
precision = precision_score(y_test, y_pred, average="weighted")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.0073435187790279076


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [158]:
sensibilidad = recall_score(y_test, y_pred, average="weighted")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.024880889359449446


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [160]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.007583295065245608


In [161]:
df_coef.loc[6] = ['score_buro ', '7', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 8

In [210]:
Vars_Indep= df2[['porc_eng', 'precio', 'descuento']]
Var_Dep= df2['limite_credito']

In [189]:
X= Vars_Indep
y= Var_Dep

In [190]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [191]:
escalar = StandardScaler()

In [192]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [193]:
algoritmo = LogisticRegression()

In [194]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [196]:
y_pred = algoritmo.predict(X_test)
y_pred

array([7000., 6500., 4000., ..., 6500., 4500., 7000.])

#### Coeficientes :

In [197]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[  0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   7   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   3   0   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   8   4   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 121  86  20   0   0   0   0   2   0   0   0   0   0   0]
 [  0   0   0   0  27 293  22   0   0   0   0   6   1   0   0   0   0   0]
 [  0   0   0   0  27 193  43   0   0   0   0   3   0   0   0   0   0   0]
 [  0   0   0   0   1  29   0   0   0   0   0  12   0   0   0   0   0   0]
 [  0   0   0   0  17 123   5   0   6   0   0  38   2   0   0   0   0   0]
 [  0   0   0   0   3  90   1   0   0   0   0  22   3   0   0   0   0   0]
 [  0   0   0   0   2  27   0   0   0   0   0  38   3   0   0   0   0   0]
 [  0   0   0   0   3  21   0   0   0   0   0 165  47   0   0   0   0   0]
 [  0   0   0   0   7   6   0   0   0   0   0  74  98   0   0   0   0  11]
 [  

In [204]:
precision = precision_score(y_test, y_pred, average="weighted")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.4004579838526431


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [205]:
sensibilidad = recall_score(y_test, y_pred, average="weighted")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.4007411328745368


In [206]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.3191762607182778


In [207]:
df_coef.loc[7] = ['limite_credito', '8', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 9

In [211]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['semana_actual']

In [212]:
X= Vars_Indep
y= Var_Dep

In [213]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [214]:
escalar = StandardScaler()

In [215]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [216]:
algoritmo = LogisticRegression()

In [217]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [218]:
y_pred = algoritmo.predict(X_test)
y_pred

array([26., 13., 13., ..., 13., 13., 13.])

#### Coeficientes :

In [219]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [227]:
precision = precision_score(y_test, y_pred, average="micro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.12863949179460032


In [225]:
sensibilidad = recall_score(y_test, y_pred, average="weighted")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.12863949179460032


In [226]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.04893014443950319


In [228]:
df_coef.loc[8] = ['semana_actual', '9', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 10

In [229]:
Vars_Indep= df2[['score_buro', 'precio', 'riesgo']]
Var_Dep= df2['edad_cliente']

In [230]:
X= Vars_Indep
y= Var_Dep

In [231]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [232]:
escalar = StandardScaler()

In [233]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [234]:
algoritmo = LogisticRegression()

In [235]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [236]:
y_pred = algoritmo.predict(X_test)
y_pred

array([31., 34., 31., ..., 29., 34., 45.])

#### Coeficientes :

In [237]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [248]:
precision = precision_score(y_test, y_pred, average="micro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.058231868713605084


In [250]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.035422013340354254


In [251]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.031103876018888112


In [253]:
df_coef.loc[9] = ['edad_cliente', '10', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Coeficientes de precisión, exactitud y sensibilidad :

In [254]:
df_coef

Variable Analisis  Precision  Exactitud  Sensibilidad
0            puntos        1       0.14       0.13          0.12
1       costo_total        2       0.00       0.01          0.00
2            semana        3       0.02       0.01          0.00
3            status        4       0.29       0.33          0.31
4  pagos_realizados        5       0.02       0.04          0.02
5          enganche        6       0.00       0.02          0.00
6       score_buro         7       0.01       0.02          0.01
7    limite_credito        8       0.40       0.40          0.32
8     semana_actual        9       0.13       0.13          0.05
9      edad_cliente       10       0.06       0.04          0.03