<a href="https://colab.research.google.com/github/JUMITO737/Regresion_Logistica/blob/main/Act_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Actividad 7 (Regresión Logística)

1. **Utilizar** el nuevo repositorio con el nombre: **Regresión Logistica**

2. **Agregar** el archivo: **“Cuentas_credicel.csv”**

3. **Realiza** las acciones de preprocesamiento necesarias: **Nulos y Outliers**

4. **Analizar** 10 casos de correlación logística que existe entre diferentes variables de nuestra base de datos, aplicando la herramienta de **“Regresión Logística”**

5. **Convertir** las variables **que sean necesarias** en variables de tipo  dicotómica con las categorías que se consideren pertinentes, aplicando la herramienta de  **“Regresión Logística”**

6. **Realizar** una tabla de todos los coeficientes de **precisión, exactitud y sensibilidad** obtenidos para cada correlación analizada, según sea el caso.

7. **Crear** los archivos requeridos en **Google Colab** y respaldarlos en **GitHub.**

8. **Generar** un reporte comparativo sobre los análisis realizados y subirlo a **GitHub, en formato pdf.**

9. **Subir** el link del repositorio en CANVAS para **“Evaluación”**

## Librerias :

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

## Archivos :

In [ ]:
df = pd.read_csv('cuentas_credicel.csv', encoding='latin-1')
df.head(5)

<ipython-input-2-c71743e22efc>:1: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('cuentas_credicel.csv', encoding='latin-1')


folio       tag  folio_solicitud             fecha     marca  \
0         3  HDNAWQ3A               30  12/11/2021 19:00       ZTE   
1         4  M418YNR4               33  12/11/2021 19:15  MOTOROLA   
2         5  SZ7V3NZT               37  13/11/2021 14:13       ZTE   
3         6  9I08UIQZ               38  13/11/2021 15:45       ZTE   
4         7  JMF4LKYU               44  13/11/2021 16:10  MOTOROLA   

                         modelo plazo  precio  enganche  descuento  ...  \
0            Blade A3 2020 RO B   26S  1949.0     780.0        0.0  ...   
1  LTE XT2097-12 E7I POWER Azul   13S  2999.0    1050.0        0.0  ...   
2            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0  ...   
3            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0  ...   
4                         G10 B   39S  4299.0    1075.0        0.0  ...   

   porc_eng  limite_credito  semana_actual  cp_cliente edad_cliente  \
0     40.02            5000             26         NaN         23.0   
1     35.01            6000             13         NaN         60.0   
2     25.01               0             74         NaN         58.0   
3     25.01            7000             13         NaN         42.0   
4     25.01            7000             74         NaN         33.0   

    cd_cliente  edo_cliente                    cd_venta edo_venta  \
0            0            0                   Tantoyuca  Veracruz   
1      PUEBLA          PUE.  Heroica Puebla de Zaragoza    Puebla   
2    TANTOYUCA         VER.                           0         0   
3  AMXTLAN PUE          NaN                    Zacatlan    Puebla   
4   TANTOYUCA          VER.                   Tantoyuca  Veracruz   

                 curp  
0  AEVM980413MVZNDR02  
1  ZALC610119MPLPRR07  
2                   0  
3  SAMJ790115MPLNRS02  
4  TEHF880707HVZRRR07  

[5 rows x 39 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   folio            22735 non-null  int64  
 1   tag                 22735 non-null  object 
 2   folio_solicitud     22735 non-null  int64  
 3   fecha               22735 non-null  object 
 4   marca               22735 non-null  object 
 5   modelo              22735 non-null  object 
 6   plazo               22735 non-null  object 
 7   precio              22735 non-null  float64
 8   enganche            22735 non-null  float64
 9   descuento           22735 non-null  float64
 10  semana              22735 non-null  int64  
 11  monto_financiado    22735 non-null  float64
 12  costo_total         22735 non-null  int64  
 13  monto_accesorios    22735 non-null  float64
 14  agente_venta        22735 non-null  object 
 15  dis_venta           22735 non-null  object 
 16  stat

## Limpieza :

### Valores Nulos

In [ ]:
df.isnull().sum()

folio                 0
tag                      0
folio_solicitud          0
fecha                    0
marca                    0
modelo                   0
plazo                    0
precio                   0
enganche                 0
descuento                0
semana                   0
monto_financiado         0
costo_total              0
monto_accesorios         0
agente_venta             0
dis_venta                0
status                   0
fraude                   0
empresa                 13
inversion                0
pagos_realizados         0
reautorizacion           0
fecha_ultimo_pago     3356
fecha_pago_proximo    3356
status_cuenta         3314
puntos                   0
riesgo                   0
score_buro               0
razones_buro          7340
porc_eng                 0
limite_credito           0
semana_actual            0
cp_cliente            7243
edad_cliente             9
cd_cliente               0
edo_cliente              8
cd_venta                 0
e

In [ ]:
df1 =df.fillna(method="bfill")
df1.isnull().sum()

folio               0
tag                    0
folio_solicitud        0
fecha                  0
marca                  0
modelo                 0
plazo                  0
precio                 0
enganche               0
descuento              0
semana                 0
monto_financiado       0
costo_total            0
monto_accesorios       0
agente_venta           0
dis_venta              0
status                 0
fraude                 0
empresa                0
inversion              0
pagos_realizados       0
reautorizacion         0
fecha_ultimo_pago      0
fecha_pago_proximo     0
status_cuenta         35
puntos                 0
riesgo                 0
score_buro             0
razones_buro           0
porc_eng               0
limite_credito         0
semana_actual          0
cp_cliente             0
edad_cliente           0
cd_cliente             0
edo_cliente            0
cd_venta               0
edo_venta              0
curp                   0
dtype: int64

In [ ]:
df1 = df1.fillna(method="ffill")
df1.isnull().sum()

folio              0
tag                   0
folio_solicitud       0
fecha                 0
marca                 0
modelo                0
plazo                 0
precio                0
enganche              0
descuento             0
semana                0
monto_financiado      0
costo_total           0
monto_accesorios      0
agente_venta          0
dis_venta             0
status                0
fraude                0
empresa               0
inversion             0
pagos_realizados      0
reautorizacion        0
fecha_ultimo_pago     0
fecha_pago_proximo    0
status_cuenta         0
puntos                0
riesgo                0
score_buro            0
razones_buro          0
porc_eng              0
limite_credito        0
semana_actual         0
cp_cliente            0
edad_cliente          0
cd_cliente            0
edo_cliente           0
cd_venta              0
edo_venta             0
curp                  0
dtype: int64

In [ ]:
df1.isnull().sum().sum()

0

In [ ]:
df1.shape

(22735, 39)

### Outliners

In [ ]:
df1['limite_credito'] = pd.to_numeric(df1['limite_credito'], errors='coerce')
df1['limite_credito'].fillna(7000, inplace=True)

In [ ]:
numeric_columns = df1.select_dtypes(include=['number'])
categoric_columns = df1.select_dtypes(include=['object'])

In [ ]:
y=numeric_columns
Limite_Superior= y.mean() + 3* y.std()
Limite_Inferior= y.mean() - 3 * y.std()
print("Limite Superior Permitido", Limite_Superior)
print("Limite Inferior Permitido", Limite_Inferior)

Limite Superior Permitido folio             31323.107698
folio_solicitud     127723.906961
precio                8081.558082
enganche              2356.496845
descuento              478.215020
semana                 541.287392
monto_financiado      6366.317810
costo_total          12857.588246
monto_accesorios       191.260880
status                   2.611178
fraude                   0.864131
inversion                1.511599
pagos_realizados        39.306132
reautorizacion           0.578086
puntos                  48.354233
riesgo                  58.456322
score_buro            1142.021000
porc_eng                45.711306
limite_credito       12330.101115
semana_actual           64.380898
edad_cliente           422.314014
dtype: float64
Limite Inferior Permitido folio            -8301.055796
folio_solicitud    -36023.715538
precio                -87.484900
enganche             -503.622066
descuento            -321.263535
semana                -65.792692
monto_financiado     

In [ ]:
df2 = numeric_columns[(y<=Limite_Superior)&(y>=Limite_Inferior)]

In [ ]:
df2 = df2.fillna(round(df2.mean(),1))

In [ ]:
df2 = pd.concat([df2, categoric_columns], axis=1)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   folio            22735 non-null  int64  
 1   folio_solicitud     22735 non-null  int64  
 2   precio              22735 non-null  float64
 3   enganche            22735 non-null  float64
 4   descuento           22735 non-null  float64
 5   semana              22735 non-null  float64
 6   monto_financiado    22735 non-null  float64
 7   costo_total         22735 non-null  float64
 8   monto_accesorios    22735 non-null  float64
 9   status              22735 non-null  float64
 10  fraude              22735 non-null  float64
 11  inversion           22735 non-null  int64  
 12  pagos_realizados    22735 non-null  float64
 13  reautorizacion      22735 non-null  float64
 14  puntos              22735 non-null  float64
 15  riesgo              22735 non-null  float64
 16  scor

In [ ]:
df2.isnull().sum().sum()

0

## Actividad :

In [ ]:
df2.sample(10)

folio  folio_solicitud   precio  enganche  descuento  semana  \
20083     20268            83937  5599.00    1576.0        0.0   222.0   
17678     17852            72909  3649.00     966.0      400.0   186.0   
5703       5838            22000  3969.20    1237.0        0.0   387.0   
5498       5633            21271  3699.00     765.0        0.0   162.0   
21914     22119            92719  6899.00    2149.0        0.0   329.0   
17923     18097            73868  2122.82     629.0        0.0   103.0   
8389       8531            33101  3449.00     826.0        0.0   182.0   
15836     15998            65374  2689.83     641.0        0.0   142.0   
5227       5362            20341  2004.82     577.0        0.0   165.0   
21047     21238            88526  4500.00    1372.0        0.0   217.0   

       monto_financiado  costo_total  monto_accesorios  status  ...  \
20083           4023.00       8658.0               0.0     1.0  ...   
17678           2683.00       4836.0               0.0     1.0  ...   
5703            3043.80       5588.6               0.0     1.0  ...   
5498            2934.00       6318.0               0.0     2.0  ...   
21914           4750.00       8554.0               0.0     1.0  ...   
17923           1493.82       2678.0               0.0     1.0  ...   
8389            2623.00       4732.0               0.0     1.0  ...   
15836           2048.83       3692.0               0.0     1.0  ...   
5227            1427.82       2145.0               0.0     1.0  ...   
21047           3128.00       5642.0               0.0     1.0  ...   

       fecha_ultimo_pago  fecha_pago_proximo  status_cuenta  razones_buro  \
20083   09/04/2023 00:00    18/04/2023 00:00      Corriente   E2,J0,E0,G1   
17678   16/04/2023 00:00    24/04/2023 00:00      Corriente   K0,E2,F7,D7   
5703    15/10/2022 00:00    22/10/2022 00:00           Mora            C4   
5498    13/01/2023 00:00    20/01/2023 00:00           Mora            C4   
21914   15/04/2023 00:00    22/04/2023 00:00      Corriente            C2   
17923   11/04/2023 00:00    18/04/2023 00:00      Corriente   K0,J0,D7,E2   
8389    08/04/2023 00:00    17/04/2023 00:00         Atraso            C2   
15836   15/04/2023 00:00    22/04/2023 00:00      Corriente   K0,J0,E2,D8   
5227    26/08/2022 00:00    12/12/2022 00:00           Mora            C4   
21047   27/03/2023 00:00    03/04/2023 00:00           Mora            C2   

       cp_cliente       cd_cliente  edo_cliente                    cd_venta  \
20083       62573         JIUTEPEC          MOR                    Jiutepec   
17678       97390             UMAN          YUC                        Uman   
5703        93080  EMILIANO ZAPATA         TAB.             Emiliano Zapata   
5498        93080      HUEYTLALPAN         PUE.                    Zacatlan   
21914       76617          TOLIMAN          QRO                     Toliman   
17923       90140          PANOTLA         TLAX    Tlaxcala de Xicohtencatl   
8389        97700          TIZIMIN          YUC                     Tizimin   
15836       95600    PLAYA VICENTE          VER               Playa Vicente   
5227        93080           PUEBLA         PUE.  Heroica Puebla De Zaragoza   
21047       72219           PUEBLA          PUE  Heroica Puebla De Zaragoza   

       edo_venta                curp  
20083    Morelos  BATM920519HDFRRR01  
17678    Yucatan  LOCD920905MTCPHL05  
5703     Tabasco  FOBL830613MTCLLZ13  
5498      Puebla  GAMM000223HPLNRTA0  
21914  Queretaro  GULO871004HQTDNS04  
17923     Puebla  BEPJ700305MTLRRN04  
8389     Yucatan  CABI020611HYNHLSA2  
15836   Veracruz  ROPI950625MVZDRR06  
5227      Puebla  COFJ710224HPLRLM01  
21047     Puebla  RALY030514MPLMPRA3  

[10 rows x 39 columns]

In [ ]:
df_coef = pd.DataFrame(columns=['Variable', 'Analisis', 'Precision', 'Exactitud','Sensibilidad'])

### Remplazador de variables

In [ ]:
df3 = df2.copy()

In [ ]:
unico = np.unique(df2['riesgo'])
print(unico)

[-47.   -46.25 -46.1  ...  56.25  57.1   58.  ]


1 = Relacionado con Celular

0 = No relacionado con celulares

In [ ]:
#df3['marca']= df3['marca'].replace(['ALCATEL', 'Alcatel', 'HISENSE', 'Hisense', 'MOTOROLA', 'Motorola', 'NOKIA', 'Nokia', 'SAMSUNG','Samsung', 'TCL', 'TECHPAD', 'TECNO MOBILE', 'VIVO', 'Vivo','WIKO', 'ZTE'], "1")
#df3['marca']= df3['marca'].replace(['LG','Lanix','RT'], "0")
#df3.sample(5)

In [ ]:
#df3['marca'] = pd.to_numeric(df3['marca'])

In [ ]:
unico2 = np.unique(df2['agente_venta'])
unico2

array(['Abigail Heredia Aguilar', 'Abraham Diaz Melendez',
       'Abraham Hernandez Avila', ..., 'Zuleima Paulino Santiago',
       'Zuleyma Castillo Salmeron', 'Zuleymi Anahi Chan Correa'],
      dtype=object)

### Analisis 1

In [ ]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['tag']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['FPTED1EM', '6AQ89543', '6PGRBC8N', ..., 'IUE8938Q', 'SUCLLWNM',
       '7UKKFBJR'], dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.0


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.0


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.0


In [ ]:
df_coef.loc[0] = ['tag', '1', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 2

In [ ]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['marca']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['ZTE', 'Samsung', 'Samsung', ..., 'Samsung', 'ZTE', 'Samsung'],
      dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0   21    0    0    0    0    0   44    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0   13    0    0    0    0    0   14    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    1
     0   43    0    1    0    0    0   32    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    4
     0   94    0    2    0    0    0   22    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    1    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    1    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    4    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    2    0    0    0    0    0   27    0]
 [   0    0    0   

In [ ]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.08747003880830923


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.08242302896899364


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.06771109279462875


In [ ]:
df_coef.loc[1] = ['marca', '2', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 3

In [ ]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['modelo']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['A03', 'A03', 'BLADE A3 2020 Gris', ..., 'A03', 'A03s', 'A03'],
      dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
precision = precision_score(y_test, y_pred, average="micro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.2333968626301129


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.019087184288289833


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.012736315738760025


In [ ]:
df_coef.loc[2] = ['semana', '3', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 4

In [ ]:
Vars_Indep= df2[['enganche', 'monto_financiado', 'descuento']]
Var_Dep= df3['agente_venta']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Nain Raymundo Mex Hau', 'Nain Raymundo Mex Hau',
       'David Espinoza Medina', ..., 'David Espinoza Medina',
       'David Espinoza Medina', 'Jose Gonzalo Sanchez CanteV'],
      dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.00031716121462128916


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.0021850889065160514


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.0004292564267599339


In [ ]:
df_coef.loc[3] = ['agente_venta', '4', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 5

In [ ]:
Vars_Indep= df2[['enganche', 'precio', 'inversion']]
Var_Dep= df2['empresa']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['microtec', 'microtec', 'microtec', ..., 'microtec', 'servicel',
       'microtec'], dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.03498773599747404


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.0353842586512808


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.031117830618593044


In [ ]:
df_coef.loc[4] = ['empresa', '5', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 6

In [ ]:
#bins = [0, 1, 2, 3, 4, 5]  # Define los intervalos que dividen las etiquetas

# Utiliza pd.cut para discretizar las etiquetas continuas en categorías
#df2['riesgo'] = pd.cut(df2['riesgo'], bins)

In [ ]:
Vars_Indep= df2[['precio', 'riesgo', 'descuento']]
Var_Dep= df2['dis_venta']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['svc003', 'svc011', 'mic0912', ..., 'svc001', 'svc001', 'mic014'],
      dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
precision = precision_score(y_test, y_pred, average="weighted")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.007197794312088065


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="weighted")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.039146690125357375


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.007651032384013419


In [ ]:
df_coef.loc[5] = ['dis_venta', '6', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 7

In [ ]:
Vars_Indep= df2[['score_buro', 'precio', 'riesgo']]
Var_Dep= df2['razones_buro']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['C4', 'C2', 'K0,J0,E2,D8', ..., 'K0,J0,E2,D8', 'C4', 'J0,G1,E0,E2'],
      dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
precision = precision_score(y_test, y_pred, average="weighted")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.32370180656975955


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="weighted")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.4138689341738748


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.3508945452821602


In [ ]:
df_coef.loc[6] = ['razones_buro', '7', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 8

In [ ]:
Vars_Indep= df2[['porc_eng', 'limite_credito', 'descuento']]
Var_Dep= df2['cd_venta']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Heroica Puebla De Zaragoza', 'Piste',
       'Heroica Puebla De Zaragoza', ..., 'Heroica Puebla De Zaragoza',
       'Heroica Puebla De Zaragoza', 'Heroica Puebla De Zaragoza'],
      dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[43  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [ ]:
precision = precision_score(y_test, y_pred, average="weighted")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.02649906274032727


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="weighted")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.12432194692860285


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.037925901459619514


In [ ]:
df_coef.loc[7] = ['cd_venta', '8', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 9

In [ ]:
Vars_Indep= df2[['porc_eng', 'precio', 'descuento']]
Var_Dep= df2['edo_venta']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Puebla', 'Puebla', 'Puebla', ..., 'Puebla', 'Puebla', 'Puebla'],
      dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0   30    0    0    0    0    0    0    0    0    4    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0   15    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0  134    0    0    0    0    0    0    0    0    7    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0   67    0    0    0    0    0    0    0    0  106    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0   23    0    0    0    0    0    0    0    0   35    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    5    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0   30    0    0    0 

In [ ]:
precision = precision_score(y_test, y_pred, average="micro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.43629966280604016


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="weighted")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.43629966280604016


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.315403450777365


In [ ]:
df_coef.loc[8] = ['edo_venta', '9', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Analisis 10

In [ ]:
Vars_Indep= df2[['score_buro', 'precio', 'riesgo']]
Var_Dep= df2['status_cuenta']

In [ ]:
X= Vars_Indep
y= Var_Dep

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
escalar = StandardScaler()

In [ ]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
algoritmo = LogisticRegression()

In [ ]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Corriente', 'Corriente', 'Corriente', ..., 'Corriente', 'Mora',
       'Corriente'], dtype=object)

#### Coeficientes :

In [ ]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0  696    0  297]
 [   0    0   35    0   30]
 [   0    0 2877    0  425]
 [   0    0  404    0  216]
 [   0    0  835    0 1006]]


In [ ]:
precision = precision_score(y_test, y_pred, average="micro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.5692713678346284


In [ ]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.28354645564010555


In [ ]:
puntajef1 = f1_score(y_test, y_pred, average="weighted")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.484161711487971


In [ ]:
df_coef.loc[9] = ['status_cuenta', '10', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

### Coeficientes de precisión, exactitud y sensibilidad :

In [ ]:
df_coef

Variable Analisis  Precision  Exactitud  Sensibilidad
0            tag        1       0.00       0.00          0.00
1          marca        2       0.09       0.08          0.07
2         semana        3       0.23       0.02          0.01
3   agente_venta        4       0.00       0.00          0.00
4        empresa        5       0.03       0.04          0.03
5      dis_venta        6       0.01       0.04          0.01
6   razones_buro        7       0.32       0.41          0.35
7       cd_venta        8       0.03       0.12          0.04
8      edo_venta        9       0.44       0.44          0.32
9  status_cuenta       10       0.57       0.28          0.48